os: osx
osx_image: xcode12.5
language: swift
env: SWIFT_SNAPSHOT=5.4
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/NestSegment.xcworkspace -scheme NestSegment-Example -sdk iphonesimulator14.5 ONLY_ACTIVE_ARCH=NO -enableCodeCoverage YES | xcpretty
- pod lib lint
